### ISSUE TITLE
SD Solver numpy Error

### ISSUE THREAD

**Issue by howitzer99** [Bismuth-Consultancy-BV/MLOPs#136]
I've getting errors when trying to re-create the Viewport To Texture workflow.  Size is set to the same 512x512 in the camera and the sd_latent_noise_generate nodes.
The issue is that the downstream sd_solver node is throwing the following error:

**Error 
Invalid source /obj/Viewport_To_Texture/sd_solver1/solver.
(Error: Python error: Traceback (most recent call last):
File "<stdin>", line 48, in <module>
File "E:\AI/MLOPs/scripts/python\mlops_image_utils.py", line 47, in colored_points_to_numpy_array
r = numpy.array(geo.pointFloatAttribValues("r"), dtype=numpy.float32).reshape(
ValueError: cannot reshape array of size 16384 into shape (512,512)
).** 

Houdini 20.0.547
numpy 1.26.3
A1111 is up to date

**Comment by spelafort** [comment]
I'm getting the exact same issue (same version of Houdini and numpy). Did you ever find a fix?

**Comment by Ambrosiussen** [comment]
Hi,

This is because you probably have an old file you opened. If you make a new node instance it should work :)
If you want to keep working in your old files, change the asset version to be the latest for everything (if present)

Example:
![image](https://github.com/Bismuth-Consultancy-BV/MLOPs/assets/23486196/160b177a-d7ef-4d35-a9a8-9600fdcbe59d)
